name: CI Workflow

on:
  workflow_dispatch:

jobs:
  notify-release:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.CYPRESSNOTIFIER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq (JSON processor)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get latest release URL
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.html_url')
          echo "LATEST_RELEASE_URL=$LATEST_RELEASE_URL" >> $GITHUB_ENV
        shell: bash

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.CYPRESSNOTIFIER }}
          LATEST_RELEASE_URL: ${{ env.LATEST_RELEASE_URL }}
        run: |
          if [ -n "$LATEST_RELEASE_URL" ]; then
            MESSAGE="El último release está disponible: $LATEST_RELEASE_URL"
            echo "Enviando mensaje a Slack: $MESSAGE"
            curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK
          else
            echo "No se encontró una URL del último release."
          fi
        shell: bash